#!/usr/bin/with-contenv bash
# ==============================================================================
# Node-RED
# Starts Node-RED
# ==============================================================================

echo "Starting Node-RED..."

cd /usr/src/node-red
exec npm start --cache /app/.npm -- --userDir /app