os: linux

language: shell

branches:
  only:
    - master

services:
  - docker

install:
  - docker pull gittools/gitversion:5.0.2-linux

before_script:
  - export GitVersion_FullSemVer=$(docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.0.2-linux /repo -output json -showvariable FullSemVer)

env:
  global:
    - DOCKERHUB="stecky/node-red"

jobs:
  include:
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -t ${DOCKERHUB}:latest .
        - docker tag ${DOCKERHUB}:latest ${DOCKERHUB}:${GitVersion_FullSemVer}
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB}:${GitVersion_FullSemVer}
        - docker push ${DOCKERHUB}:latest