#!/usr/bin/with-contenv bash

apt-get update && apt-get install -y \
    ack=2.24-1 \
    bsdtar=3.3.3-4+deb10u1 \
    build-essential=12.6 \
    colordiff=1.0.18-1 \
    git=1:2.20.1-2+deb10u3 \
    iputils-ping=3:20180629-2+deb10u1 \
    locales=2.28-10 \
    mariadb-client=1:10.3.23-0+deb10u1 \
    mosquitto-clients=1.5.7-1+deb10u1 \
    net-tools=1.60+git20180626.aebd88e-1 \
    nmap=7.70+dfsg1-6+deb10u1 \
    openssh-client=1:7.9p1-10+deb10u2 \
    openssl=1.1.1d-0+deb10u3 \
    wget=1.20.1-1.1 \
    uuid-runtime=2.33.1-0.1 \
    zsh=5.7.1-1

sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen

mkdir -p /root/.code-server/extensions

uuid=$(uuidgen)

while read -r ext; do \
    extension="${ext%%#*}" \
    vendor="${extension%%.*}"; \
    slug="${extension#*.}"; \
    version="${ext##*#}"; \
    \
    echo "Installing vscode extension: ${slug} by ${vendor} @ ${version} "; \
    \
    echo "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"; \
    curl -JL --retry 5 -o "/tmp/${extension}-${version}.vsix" \
        -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" \
        -H "x-market-user-id: ${uuid}" \
        "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"; \
    mkdir -p "/root/.code-server/extensions/${extension}-${version}"; \
    bsdtar --strip-components=1 -xf "/tmp/${extension}-${version}.vsix" \
                -C "/root/.code-server/extensions/${extension}-${version}" extension; \
    [ $? -ne 0 ] && exit 1; \
    sleep 1; \
done < /vscode.extensions

ls -la /root/.code-server/extensions/

curl -L -s -o /usr/bin/ha \
        "https://github.com/home-assistant/cli/releases/download/4.4.1/ha_${ARCH}"

chmod a+x /usr/bin/ha

git clone --branch master --single-branch --depth 1 \
        "git://github.com/robbyrussell/oh-my-zsh.git" ~/.oh-my-zsh

git clone --branch master --single-branch --depth 1 \
        "git://github.com/zsh-users/zsh-autosuggestions" \
        ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

git clone --branch master --single-branch --depth 1 \
        "git://github.com/zsh-users/zsh-syntax-highlighting.git" \
        ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

sed -i -e "s#bin/bash#bin/zsh#" /etc/passwd

update-alternatives --install /usr/bin/python python /usr/bin/python3 10

pip3 install --no-cache-dir -r /requirements.txt

apt-get purge -y --auto-remove \
        bsdtar \
        build-essential \
        python3-dev \
        uuid-runtime

find /usr/local/lib/python3.7/ -type d -name tests -depth -exec rm -rf {} \;
find /usr/local/lib/python3.7/ -type d -name test -depth -exec rm -rf {} \;
find /usr/local/lib/python3.7/ -name __pycache__ -depth -exec rm -rf {} \;
find /usr/local/lib/python3.7/ -name "*.pyc" -depth -exec rm -f {} \;

rm -fr \
    /tmp/* \
    /var/{cache,log}/* \
    /var/lib/apt/lists/*
