#!/usr/bin/with-contenv bash
# ==============================================================================
# Mosquitto MQTT Broker
# Sets permissions before running
# ==============================================================================

set -e

# Set permissions
user="$(id -u)"
if [ "$user" = '0' ]; then
	[ -d "/mosquitto" ] && chown -R mosquitto:mosquitto /mosquitto || true
fi